name: Hola Cesar

on:
  push:

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ejecutar script
        run: python hola_mundo.py
